const app = document.getElementById('app');
const pages = {
  home: `
    <section class="section hero">
      <div>
        <div class="eyebrow">Professional commercial cleaning services</div>
        <h1>A Cleaner Space.<br>A Better Image.<br><span>Every Time.</span></h1>
        <p class="lead">J&B Elite Commercial Cleaning LLC delivers reliable, detailed and professional cleaning for businesses across New York.</p>
        <div class="hero-badges">
          <div class="badge"><i>🏢</i>Commercial<br>Cleaning</div>
          <div class="badge"><i>🛡️</i>Reliable &<br>Insured</div>
          <div class="badge"><i>👥</i>Trained<br>Professionals</div>
          <div class="badge"><i>🍃</i>Eco-Friendly<br>Products</div>
        </div>
        <div class="cta-row"><a class="btn primary" href="#quote" data-page="quote">Get Free Quote</a><a class="btn" href="#services" data-page="services">Our Services</a></div>
      </div>
      <div class="hero-visual" aria-hidden="true">
        <div class="hero-card"><img class="spray-hero" src="images/spray-bottle.png" alt=""></div>
        <div class="assistant-preview"><img src="images/juanito-hello-clean.png" alt=""><div class="speech">Hello, I’m <strong>Juanito</strong>How can I help you?</div></div>
      </div>
    </section>
    ${serving()}
    ${estimatePanel()}
    ${servicesPreview()}
    ${whyPreview()}
    ${footer()}
  `,
  services: `
    <section class="section"><div class="page-head"><div class="eyebrow">Our Services</div><h1 class="page-title">Cleaning solutions for <span>every business</span></h1><p class="lead">Choose the cleaning scope that fits your facility, schedule and budget.</p></div>${serviceCards()}${gallery()}</section>${footer()}`,
  why: `
    <section class="section split"><div><div class="eyebrow">Why Choose Us</div><h1 class="page-title">We go the extra mile for you</h1><ul class="checklist"><li>Licensed, bonded and insured</li><li>Reliable trained cleaning professionals</li><li>Flexible scheduling</li><li>Professional communication</li><li>100% satisfaction focused</li></ul><a class="btn primary" href="#quote" data-page="quote">Request a Quote</a></div><div class="photo-mock"><div class="photo-tile">Office cleaning</div><div class="photo-tile">Medical offices</div><div class="photo-tile">Restaurants</div><div class="photo-tile">Post-construction</div></div></section>${footer()}`,
  process: `
    <section class="section"><div class="page-head"><div class="eyebrow">Our Process</div><h1 class="page-title">Simple, professional and reliable</h1><p class="lead">From first contact to quality checks, our workflow keeps the service clear and organized.</p></div><div class="process-steps"><div class="step"><h3>Request</h3><p>Tell us about your facility, service type and preferred frequency.</p></div><div class="step"><h3>Walkthrough</h3><p>We review the scope, special areas and cleaning priorities.</p></div><div class="step"><h3>Proposal</h3><p>You receive a clear estimate with scope, schedule and service plan.</p></div><div class="step"><h3>Service</h3><p>Our team starts the cleaning program with quality follow-up.</p></div></div></section>${footer()}`,
  areas: `
    <section class="section"><div class="page-head"><div class="eyebrow">Service Areas</div><h1 class="page-title">Proudly serving local businesses</h1><p class="lead">Commercial cleaning services across Westchester, Bronx and Manhattan.</p></div>${serving()}<div class="areas-grid"><div class="area">Yonkers</div><div class="area">Westchester County</div><div class="area">White Plains</div><div class="area">New Rochelle</div><div class="area">Mount Vernon</div><div class="area">Bronx</div><div class="area">Manhattan</div><div class="area">Mamaroneck</div><div class="area">Bronxville</div></div></section>${footer()}`,
  estimate: `<section class="section">${estimatePanel()}</section>${footer()}`,
  contact: `
    <section class="section"><div class="page-head"><div class="eyebrow">Contact</div><h1 class="page-title">Let’s talk about your cleaning needs</h1><p class="lead">Use the quote form and our team will contact you to confirm details.</p></div>${quoteForm()}</section>${footer()}`,
  quote: `<section class="section"><div class="page-head"><div class="eyebrow">Free Quote</div><h1 class="page-title">Request your commercial cleaning quote</h1><p class="lead">Complete the form below. Include square footage, cleaning frequency and the type of facility.</p></div>${quoteForm()}</section>${footer()}`
};
function serving(){return `<div class="serving"><strong>📍 Proudly Serving</strong><span>Yonkers</span><span>Westchester County</span><span>White Plains</span><span>New Rochelle</span><span>Mount Vernon</span><span>Bronx</span><span>Manhattan</span></div>`}
function serviceCards(){return `<div class="cards"><div class="card"><img src="images/example-office.svg" alt="Office cleaning"><h3>Office Cleaning</h3><p>Keep your workplace clean, healthy and productive with scheduled professional cleaning.</p></div><div class="card"><img src="images/example-medical.svg" alt="Medical office cleaning"><h3>Medical Office Cleaning</h3><p>Disinfection and sanitation for medical and dental practices.</p></div><div class="card"><img src="images/example-restaurant.svg" alt="Restaurant cleaning"><h3>Restaurant Cleaning</h3><p>Kitchen deep cleaning and dining area maintenance.</p></div><div class="card"><img src="images/example-bank.svg" alt="Bank cleaning"><h3>Bank Cleaning</h3><p>Professional cleaning with attention to detail and security.</p></div><div class="card"><img src="images/example-construction.svg" alt="Post construction cleaning"><h3>Post-Construction</h3><p>Final cleaning after renovation, construction or build-outs.</p></div><div class="card"><img src="images/example-floor.svg" alt="Floor care"><h3>Floor Care</h3><p>Detailed floor cleaning, maintenance and presentation care.</p></div></div>`}
function servicesPreview(){return `<section class="section"><div class="page-head"><div class="eyebrow">Our Services</div><h1 class="page-title">Cleaning solutions for every business</h1></div>${serviceCards()}</section>`}
function whyPreview(){return `<section class="section split"><div><div class="eyebrow">Why Choose Us</div><h1 class="page-title">We go the extra mile for you</h1><ul class="checklist"><li>Licensed, bonded & insured</li><li>Highly trained cleaning professionals</li><li>Flexible scheduling</li><li>100% satisfaction focused</li></ul><a class="btn primary" href="#why" data-page="why">Learn More</a></div><div class="photo-mock"><div class="photo-tile">Professional crews</div><div class="photo-tile">Detail cleaning</div><div class="photo-tile">Reliable schedules</div><div class="photo-tile">Quality checks</div></div></section>`}
function estimatePanel(){return `<div class="panel"><div class="page-head"><div class="eyebrow">Instant Estimate</div><h1 style="color:#fff;margin:12px 0;font-size:44px">Quick commercial cleaning calculator</h1><p>This is an estimated starting range. Final price depends on scope, walkthrough and cleaning frequency.</p></div><div class="estimate-grid"><div><div class="field"><label>Square Feet</label><input id="sqft" type="number" value="3000" min="500"></div><div class="field"><label>Frequency</label><select id="freq"><option value="1">One Time</option><option value="4">Weekly</option><option value="8">Twice Weekly</option><option value="20">Daily</option><option value="2">Biweekly</option><option value="1.5">Monthly</option></select></div><div class="field"><label>Cleaning Type</label><select id="type"><option value="1">Standard Cleaning</option><option value="1.25">Medical / Detail Cleaning</option><option value="1.35">Post-Construction</option><option value="1.2">Restaurant Cleaning</option></select></div></div><div><p>Estimated monthly starting range:</p><div class="price" id="price">$300 - $390</div><p>Includes labor estimate, supplies planning and recurring service review.</p><a class="btn primary" href="#quote" data-page="quote">Get Free Quote</a></div></div></div>`}
function gallery(){return `<div class="gallery"><div class="gallery-card"><b>Office Buildings</b><span>Daily or weekly maintenance</span></div><div class="gallery-card"><b>Medical Facilities</b><span>High-detail sanitation</span></div><div class="gallery-card"><b>Restaurants</b><span>Kitchen and dining areas</span></div><div class="gallery-card"><b>Banks</b><span>Clean public and staff areas</span></div><div class="gallery-card"><b>Construction Sites</b><span>Final cleaning and turnover</span></div><div class="gallery-card"><b>Floor Care</b><span>Clean presentation for clients</span></div></div>`}
function quoteForm(){return `<form class="quote-form" action="https://formspree.io/f/xzzvvgjo" method="POST"><div class="form-grid"><input name="name" placeholder="Full Name" required><input name="company" placeholder="Company Name"><input name="phone" placeholder="Phone Number" required><input name="email" type="email" placeholder="Email Address" required><select name="service"><option>Office Cleaning</option><option>Medical Office Cleaning</option><option>Restaurant Cleaning</option><option>Bank Cleaning</option><option>Post-Construction Cleaning</option><option>Other</option></select><select name="frequency"><option>Daily</option><option>Weekly</option><option>Biweekly</option><option>Monthly</option><option>One Time</option></select><textarea name="message" placeholder="Tell us about the building, square footage, schedule and cleaning needs."></textarea></div><button class="btn primary" type="submit">Submit Free Quote</button></form>`}
function footer(){return `<footer class="footer"><b>J&B Elite Commercial Cleaning LLC</b><br>Professional commercial cleaning services across New York.</footer>`}
function render(page='home'){app.innerHTML=pages[page]||pages.home; document.querySelectorAll('[data-page]').forEach(a=>a.classList.toggle('active',a.dataset.page===page)); app.focus({preventScroll:true}); window.scrollTo(0,0); bindInternalLinks(); calcBind();}
function bindInternalLinks(){document.querySelectorAll('[data-page]').forEach(el=>{el.onclick=e=>{e.preventDefault(); const p=el.dataset.page; history.pushState({page:p},'',`#${p}`); render(p); document.querySelector('.nav')?.classList.remove('open');};});}
function calcBind(){const sqft=document.getElementById('sqft'),freq=document.getElementById('freq'),type=document.getElementById('type'),price=document.getElementById('price'); if(!sqft||!freq||!type||!price)return; const update=()=>{let base=Math.max(500,+sqft.value||0)*0.10*(+freq.value)*(+type.value); let low=Math.round(base/10)*10, high=Math.round(base*1.3/10)*10; price.textContent=`$${low.toLocaleString()} - $${high.toLocaleString()}`}; [sqft,freq,type].forEach(x=>x.addEventListener('input',update)); update();}
function askJuanito(q){q=(q||'').toLowerCase(); let page='services', answer='I can help with that. I’m taking you to our services page.'; if(q.includes('price')||q.includes('estimate')||q.includes('cost')||q.includes('how much')){page='estimate';answer='For pricing, start with the quick estimate calculator. Final pricing depends on walkthrough and scope.'} else if(q.includes('area')||q.includes('bronx')||q.includes('yonkers')||q.includes('westchester')||q.includes('manhattan')){page='areas';answer='We serve Yonkers, Westchester County, White Plains, New Rochelle, Mount Vernon, Bronx and Manhattan.'} else if(q.includes('quote')||q.includes('free')){page='quote';answer='I’ll take you to the free quote form so you can send your request.'} else if(q.includes('contact')||q.includes('phone')||q.includes('email')){page='contact';answer='I’ll take you to the contact page.'} else if(q.includes('why')||q.includes('insured')||q.includes('bonded')){page='why';answer='J&B Elite is focused on reliable, professional, insured commercial cleaning.'} else if(q.includes('process')||q.includes('start')){page='process';answer='Our process is request, walkthrough, proposal and professional service.'} document.getElementById('chatAnswer').textContent=answer; history.pushState({page},'',`#${page}`); render(page);}
document.querySelector('.mobile-menu').addEventListener('click',()=>document.querySelector('.nav').classList.toggle('open'));
document.getElementById('toTop').onclick=()=>window.scrollTo(0,0);
document.getElementById('chatClose').onclick=()=>{document.getElementById('juanitoChat').classList.add('hidden');document.getElementById('chatBubble').classList.remove('hidden')};
document.getElementById('chatBubble').onclick=()=>{document.getElementById('juanitoChat').classList.remove('hidden');document.getElementById('chatBubble').classList.add('hidden')};
document.querySelectorAll('[data-ask]').forEach(b=>b.onclick=()=>askJuanito(b.dataset.ask));
document.getElementById('chatAsk').onclick=()=>askJuanito(document.getElementById('chatInput').value);
document.getElementById('chatInput').addEventListener('keydown',e=>{if(e.key==='Enter')askJuanito(e.target.value)});
window.onpopstate=()=>render(location.hash.replace('#','')||'home');
render(location.hash.replace('#','')||'home');
